version: '3'
services:

  php:
    build: ./
    volumes:
      - .:/app:cached
      - ./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/supervisord.conf:/etc/supervisord.conf
    links:
      - mariadb
      - mailcatcher
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - 8000:80
    volumes:
      - .:/app
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  mariadb:
    image: mariadb:latest
    ports:
     - 33060:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: running_time
      MYSQL_USER: running_time
      MYSQL_PASS: secret

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080

  redis:
    image: redis:3-alpine
    ports:
      - 63790:6379

volumes:
  mysql:
